project_id = "goalbud"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://goalbud.fyi"
additional_redirect_urls = ["https://goalbud.fyi/today", "https://goalbud.daniel-almeida-rambo.workers.dev/today", "http://localhost:4200/today"]

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
